### ISSUE TITLE
bugfix: card closing after client side request

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#524] opened 2023-09-30 00:11 UTC
### Description

When a user is not signed in and they expand a card on `search`, it will close when the client-side request finishes and the UI component is replaced. We want to prevent this behavior. 

![card-closing-unauthed-bug](https://github.com/arguflow/arguflow/assets/15804464/4187b887-8676-4374-bbac-ac06055e719c)

### Target(s)

`search`

### Requirement to close

- [ ] Merged PR that prevents the user from expanding the card until after the auth request and client side card fetch request have completed 

### PR commit requirements for a bounty claim

1 commit with the following message: `bugfix: card closing after client side request`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment] 2023-09-30 01:38
![image](https://github.com/arguflow/arguflow/assets/15804464/25e7614a-bb1c-488e-a47a-7f1805286006)

This is how the disabling works on the actual component

**Comment by skeptrunedev** [comment] 2023-09-30 01:39
![image](https://github.com/arguflow/arguflow/assets/15804464/01416d1a-ed44-4c14-804b-0ab9ce0a979d)

The prop is passed through the `ScoreCardArray.tsx` component

**Comment by skeptrunedev** [comment] 2023-09-30 01:43
![image](https://github.com/arguflow/arguflow/assets/15804464/d838245e-b90b-45d2-9545-ee340e9a2f06)

The problem is likely occurring because of how we are setting this signal in the `/auth` request when the user is not signed in. We likely should not do that. 

Rather, we should move the `setClientSideRequestFinished(true);` out of the second `if (response.ok)` logic branch and allow it to run regardless of whether or not the response is ok. 

This is also true of the `CollectionPage`'s usage fo `ScoreCardArray`

**Comment by Yash282003** [comment] 2023-09-30 06:15
@skeptrunedev I would like to work on this issue can you please assign it to me?

**Comment by Rhythm-08** [comment] 2023-09-30 06:31
Hello @skeptrunedev  I would like to solve this issue can you assign it to me

**Comment by skeptrunedev** [comment] 2023-09-30 15:08
> Hello @skeptrunedev I would like to solve this issue can you assign it to me

Sure! Assigned! 

Make sure to the star the repo if you have not :heart: . 

![image](https://github.com/arguflow/arguflow/assets/15804464/a7aff93c-5da8-4f46-b820-1f4350abec63)

**Comment by PrasathHari** [comment] 2023-10-01 06:59
@skeptrunedev I am seeing a duplicate request to `/card_collection/bookmark` in both `ResultsPage` and `CollectionPage` which might be the root cause of the issue. The second bookmark requests rerendes the cards. I don't think problem can be resolved by removing the first `setClientSideRequestFinished(true);`

**Comment by skeptrunedev** [comment] 2023-10-01 07:01
> @skeptrunedev I am seeing a duplicate request to `/card_collection/bookmark` in both `ResultsPage` and `CollectionPage` which might be the root cause of the issue. The second bookmark requests rerendes the cards. I don't think problem can be resolved by removing the first `setClientSideRequestFinished(true);`

I think you are right. That is likely the case for collections. However, I do still think I accurately described what is going on for search.

**Comment by skeptrunedev** [comment] 2023-10-01 07:02
> @skeptrunedev I am seeing a duplicate request to `/card_collection/bookmark` in both `ResultsPage` and `CollectionPage` which might be the root cause of the issue. The second bookmark requests rerendes the cards. I don't think problem can be resolved by removing the first `setClientSideRequestFinished(true);`

We will accept your PR if you are able to make the requested changes for sure. I guess it will be ok if it is still not working properly for collections. !

**Closed** 2023-10-01 18:20 UTC
Labels: bug, good first issue, help wanted, high priority, search, hacktoberfest
